### ISSUE TITLE
checkpoint files for evaluation

### ISSUE THREAD

**Issue by Matsuri247** [fkmajiji/Unsupervised-Spectral-Demosaicing#1]
Thank you for the nice work! Could you please provide the checkpoint files that used in the comparative experiments for evaluation?

**Comment by fkmajiji** [comment]
Thank you for your attention! I have uploaded the checkpoint at https://drive.google.com/drive/folders/1YWofUItVI4Dey-YC0B19loa94yglBBg1 and the introduction word in the Readme file.
