### ISSUE TITLE
ModuleNotFoundError:

### ISSUE THREAD

**Issue by WongYinJ** [fkmajiji/Unsupervised-Spectral-Demosaicing#3]
Error [ModuleNotFoundError: No module named 'colour_demosaicing'] in line 11 of the file lapsrn.py reported, please tell what to do, thanks!!

**Comment by fkmajiji** [comment]
This package is not used in this project. You can comment these related codes.
Or, maybe you can 'pip install colour_demosaicing'.

**Comment by WongYinJ** [comment]
> This package is not used in this project. You can comment these related codes. Or, maybe you can 'pip install colour_demosaicing'.

Thank you for your reminder. It works after being commented.
