### ISSUE TITLE
Comparison methods

### ISSUE THREAD

**Issue by Matsuri247** [fkmajiji/Unsupervised-Spectral-Demosaicing#4]
It seems that most of the comparison methods ( ANL, ItSD, PPID, SpNet, InNet) in the paper are not open-source. Did you implement these methods from scratch or find the original codes provided by the authors for the comparative experiments?  I also want to do some work on MSI demosaicing and I'm struggling on forming a benchmark for compare.

**Comment by fkmajiji** [comment]
I shared some classic spectral demosaicing methods, such as PPID, WB, ItSD, and ANL on https://github.com/fkmajiji/Collection-of-Classic-Multispectral-Demosaicing-Methods

**Comment by fkmajiji** [comment]
I remembered SpNet and InNet were from the original author by email

**Comment by Matsuri247** [comment]
Thank you very much! And would you mind also sharing the codes of SpNet and InNet?(My email is isolmisaki247@gmail.com) It would save a lot of time. I will definitely cite both of your works and these works.
