### ISSUE TITLE
data generation

### ISSUE THREAD

**Issue by Matsuri247** [fkmajiji/Unsupervised-Spectral-Demosaicing#5]
how do you prepare the 25-bands ICVL data in this paper and the 16-bands CAVE in MCAN for test set? Their original band number are 31. Is it feasible to directly pick the first 16 or 25 bands for demosaicing experiments?

**Comment by fkmajiji** [comment]
Theoretically, you should use the spectral response function of the filter to sample the 31-band data in the spectral dimension to obtain the 16/25 band data. I public one spectral sampling code at https://github.com/fkmajiji/Spectral-Image-Sampling that can be refered.

**Comment by Matsuri247** [comment]
> Theoretically, you should use the spectral response function of the filter to sample the 31-band data in the spectral dimension to obtain the 16/25 band data. I public one spectral sampling code at https://github.com/fkmajiji/Spectral-Image-Sampling that can be refered.

Yes, I've noticed that. But this code puzzled me a lot since the example image ('Cloth3.mat') is missing. So it hard for me to figure out what does this code do exactly by debugging. Before that i cannot generate my own training&testing data. Looking forward to your kindly explanation. Thanks in advance!

**Comment by fkmajiji** [comment]
You can download 'Cloth3.mat' from http://www.ok.sc.e.titech.ac.jp/res/MSI/MSIdata59.html

**Comment by Matsuri247** [comment]
Okay i can successfully run the code. Is this the sampling code that you generate the 25-band ICVL data? And how did you generate the 16-band CAVE data (with D65, DE, F12, HA illuminants) in MCAN?

**Comment by fkmajiji** [comment]
This is not exactly the same as the code I used to generate the ICVL data, but the core is the same. You can easily adapt it to be compatible with ICVL data input.

I generated 16-band CAVE data in one old project that I did not public, but my current open source sampling code can theoretically achieve this generation. You can change the illumination file 'illum-solarTT59.csv' to D65, DE, F12, HA illuminants and filter response related files 'csf_IMEC25_600-875.csv', 'cutoff_filter_response.csv' to these of one 16-band camera.

If you are not familiar with filter array-based spectral imaging, I suggest you use the NTIRE 16-band dataset that already been simulated.
