### ISSUE TITLE
MCM

### ISSUE THREAD

**Issue by Matsuri247** [fkmajiji/Unsupervised-Spectral-Demosaicing#6]
![USD_question](https://github.com/fkmajiji/Unsupervised-Spectral-Demosaicing/assets/56073360/ab310c61-f9f1-4a47-9934-f0f1609a35ae)
The code implementation of MCM in USD is different from that in your previous work MCAN (i.e., the marked part). It is quite hard for me to comprehend what happened in these lines. Looking forward to your reply.

**Comment by fkmajiji** [comment]
The modification of this section is mainly to reduce the GPU memory usage of this original code: Raw_conv = torch.matmul(cols, local_weight).permute(0, 1, 4, 2, 3). I divide cols into multiple small cols_buffs, calculate them sequentially and then concat them back to the original shape.

**Comment by Matsuri247** [comment]
> The modification of this section is mainly to reduce the GPU memory usage of this original code: Raw_conv = torch.matmul(cols, local_weight).permute(0, 1, 4, 2, 3). I divide cols into multiple small cols_buffs, calculate them sequentially and then concat them back to the original shape.

So these two MCMs actually functions the same, is it right? The difference is that the one in USD causes less GPU burden.

**Comment by fkmajiji** [comment]
Yes,  you are right
